package com.angellos.payment.dto;

import com.angellos.payment.enums.CustomerType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
public class CollectionRequestDTO {

    @NotBlank
    private String channelId;

    @JsonIgnore
    private String country;

    /**
     * AutoGenerated with code to track this transaction
     */
    private String sequenceId;

    /**
     * One amount field is required not both
     */
    private String amount;

    private String localAmount;

    private CRRecipientDTO recipient;

    private CRSourceDTO source;

    private Boolean forceAccept = false;

    @Enumerated(EnumType.STRING)
    private CustomerType customerType = CustomerType.retail;

}
