server:
  port: 8018

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    application:
      name: Rent-Payment-Service
  jackson:
    serialization:
      write-dates-as-timestamps: false

  security:
    user:
      name: angellos
      password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true

  datasource:
    #    url: jdbc:h2:mem:default
    url: jdbc:h2:file:.\data\db
    username:
    password:
    driverClassName: "org.h2.Driver"
  #    hikari:
  #      schema: public

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

yellow-card:
  uri: localhost
  port: 8018
  api-key: 'c5315180696a51ab885023bdc1ae3c0e'
  secret-key: '81473a4ca26a28203aa4a8e26afe571bf097ec5a2a5c2acd41c83a7968c4cf3b'
  base_url: 'https://sandbox.api.yellowcard.io'
  token-prefix: 'YcHmacV1 %s:%s'