server:
  port: 8018

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    application:
      name: Rent-Payment-Service
  jackson:
    serialization:
      write-dates-as-timestamps: false

  security:
    user:
      name: angellos
      password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect

#  datasource:
#    url: jdbc:postgresql://192.168.250.209:5432/tbms
#    username: softadmin
#    password: ""


  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: admin
    jpa:
      hibernate:
        ddl-auto: update

yellow-card:
  uri: localhost
  port: 8018
  api-key: 'c5315180696a51ab885023bdc1ae3c0e'
  secret-key: '81473a4ca26a28203aa4a8e26afe571bf097ec5a2a5c2acd41c83a7968c4cf3b'
  base_url: 'https://sandbox.api.yellowcard.io'
  token-prefix: 'YcHmacV1 %s:%s'

